### PR TITLE
Updated `startTime` and `duration` descriptions to match #29

### PR DESCRIPTION
**Pull request by mpb**
Updated `startTime` and `duration` descriptions to match #29

### CODE REVIEW

**Comment by igrigorik** [comment]
lgtm.

**Comment by mithro** [comment]
My only minor nit is the following text "would have been, had one been scheduled in the current frame." kind of excludes the case when there _is_ a raf scheduled.

**Comment by mpb** [comment]
What's cleaner?
with the difference between the end of the frame and the <code>startTime</code> of the frame. The end of the frame is defined as what the beginning time of the next frame's <code>requestAnimationFrame</code> callback, or if no animation frame has been requested, the beginning time which would have been used, had one been scheduled in the current frame.  (see [[!Animation-Timing]])
?

**Comment by mithro** [comment]
@mbp Do you mean "what's cleaner, the current definition or this new text?"

**Comment by mpb** [comment]
I mean what is a cleaner way to say that? And I gave one attempt at it.
-Mike

**Comment by mithro** [comment]
That is where I got stuck too :)

**Comment by mpb** [comment]
Well, what do you think of my suggestion? A little awkward, but functional?

**Comment by igrigorik** [comment]
@mpb alternative attempt...

> with the difference between the end of the frame and the startTime of the frame. The end of the frame is defined as the beginning time of the next frame's requestAnimationFrame (rAF) callback; the next frame's rAF callback is defined as callback that would have been used if it was scheduled by the application in the current frame. (see [[!Animation-Timing]])

Feel free to ignore. :)

**Comment by mbp** [comment]
Please try to mention the correct @mpb :-) thank you

**Comment by mpb** [comment]
How about

...with the difference between the end of the frame and the <code>startTime</code> of the frame. The end of the frame is defined as what the beginning time of the next frame's <code>requestAnimationFrame</code> callback (see [[!Animation-Timing]]) would have been, had one been scheduled in the current frame. If a <code>requestAnimationFrame</code> is already requested, its beginning time should be used.

**Comment by igrigorik** [comment]
:+1: ship it.

**Pull request merged**
